#ifndef WIRINGPI_VERSION_H
#define WIRINGPI_VERSION_H

#define WIRINGPI_VERSION "@PROJECT_VERSION@"

#define WIRINGPI_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define WIRINGPI_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define WIRINGPI_VERSION_PATCH @PROJECT_VERSION_PATCH@

#endif